# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'biometric' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for biometric
  pod 'Firebase/Core'
  pod 'FGRoute'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  target 'biometricTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'biometricUITests' do
    # Pods for testing
  end

end
